version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # Simulated username
      - MONGO_INITDB_ROOT_PASSWORD=password # Simulated password

volumes:
  mongodb_data:
